INSERT INTO COFFEES (NAME,COFFEEDATE,TYPE,WEIGHT,ROASTING) VALUES ('Mocha', '2019-1-1', 'Arabica', 100, 'Light');

INSERT INTO COFFEES (NAME,COFFEEDATE,TYPE,WEIGHT,ROASTING) VALUES ('Robusta', '2020-1-1', 'Arabica', 50, 'Medium');

INSERT INTO COFFEES (NAME,COFFEEDATE,TYPE,WEIGHT,ROASTING) VALUES ('Liberica', '2019-5-5', 'Arabica', 250,  'Medium');
