CREATE TABLE coffees (
  id    INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
  name  VARCHAR(70),
  coffeeDate  DATE,
  type VARCHAR(30),
  weight INT,
  roasting VARCHAR(50)
);